insert into tb_team (name, acronym, group_id, flag_url) values ('Catar', 'QAT', 1, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Equador', 'ECU', 1, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Holanda', 'NED', 1, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Senegal', 'SEN', 1, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Estados Unidos', 'USA', 2, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Inglaterra', 'ENG', 2, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Irã', 'IRN', 2, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('País de Gales', 'WAL', 2, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Argentina', 'ARG', 3, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Arábia Saudita', 'KSA', 3, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('México', 'MEX', 3, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Polônia', 'POL', 3, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Austrália', 'AUS', 4, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Dinamarca', 'DEN', 4, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('França', 'FRA', 4, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Tunísia', 'TUN', 4, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Alemanha', 'GER', 5, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Costa Rica', 'CRC', 5, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Espanha', 'ESP', 5, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Japão', 'JPN', 5, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Bélgica', 'BEL', 6, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Canadá', 'CAN', 6, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Croácia', 'CRO', 6, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Marrocos', 'MAR', 6, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Brasil', 'BRA', 7, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Camarões', 'CMR', 7, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Suíça', 'SUI', 7, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Sérvia', 'SRB', 7, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Coréia do Sul', 'KOR', 8, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Gana', 'GHA', 8, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Portugal', 'POR', 8, '');
insert into tb_team (name, acronym, group_id, flag_url) values ('Uruguai', 'URU', 8, '');